### ISSUE TITLE
how to install on Ubuntu or linux VPS ?

### ISSUE THREAD

**Issue by ingnelson** [arloor/HttpProxy#12]
Hello .

Can you give me the commands to install and run this proxy on Ubuntu VPS , please ?

i really need to use it , but i need the right commnad to install it and use it.

if you give me the commnad i will install it on my VPS . 

I will wait your response.

**Comment by arloor** [comment]
first, you need install java 8 in your vps
second, you need one TLS  certificate
then，you can install and run this proxy.

if you need more support, I am afraid that I cannot help you
