### ISSUE TITLE
Caused by: javax.net.ssl.SSLHandshakeException: error:1000009b:SSL routines:OPENSSL_internal:HTTPS_PROXY_REQUEST

### ISSUE THREAD

**Issue by xl-code-bit** [arloor/HttpProxy#16]
设置代理https后，引发异常 Caused by: javax.net.ssl.SSLHandshakeException: error:1000009b:SSL routines:OPENSSL_internal:HTTPS_PROXY_REQUEST

**Comment by arloor** [comment]
没有见过诶，详细描述下怎么使用的吧
