### ISSUE TITLE
希望能提供性能测试结果

### ISSUE THREAD

**Issue by YanzheL** [arloor/HttpProxy#7]
你好，目前Github上已经有一款比较知名的基于Netty的HTTP代理服务器[LittleProxy](https://github.com/adamfisk/LittleProxy)，想了解一下本项目和LittleProxy的性能对比。

他们好像停止开发了，所以我想找找别的解决方案。

LittleProxy的性能测试[在此](https://github.com/adamfisk/LittleProxy/tree/master/performance)

**Comment by arloor** [comment]
请自测

**Comment by arloor** [comment]
性能测试结果已经添加到readme中
