### ISSUE TITLE
xx.xx.xx.xx 应该怎么填？

### ISSUE THREAD

**Issue by luckypoem** [arloor/HttpProxy#8]
HI.
你的文章http://arloor.com/posts/other/proxynew-docker-install/#%E8%AF%B4%E6%98%8E 里说：
"编辑/etc/hosts，增加一行
xx.xx.xx.xx proxy"

这里，xx.xx.xx.xx 应该怎么填？

**Comment by arloor** [comment]
填写 国外服务器的公网ip

**Comment by luckypoem** [comment]
hi.

读了http://arloor.com/posts/other/proxynew-docker-install/#%E8%AF%B4%E6%98%8E ，我的系统是mac,  可以提供mac版的proxygo下载吗
